[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "free_range_rust"
version = "0.1.0"
description = "Python bindings for free-range-rust core logic"
requires-python = ">=3.7"
